Pandas

In [6]:
import pandas as pd

A Series is a one dimensional labelled data structure.

In [7]:
marks=pd.Series([80,75,90,85])

In [ ]:
print(marks)

0    80
1    75
2    90
3    85
dtype: int64

80,75,90,85 --> values
0,1,2,3 -->labels/index
It is one-dimensional --> like a single column of data

We can also create our own labels custom Index

In [8]:
marks=pd.Series(
    [80,75,90],
    index=["john",
           "anu",
           "Rahul"
           ]
)

In [9]:
marks

john     80
anu      75
Rahul    90
dtype: int64

Data Frame

In [10]:
data={
    "Name":[
        "John",
        "Anu",
        "Rahul"
    ],
"Age":[
    22,
    21,
    23
],
"Marks":[
    85,
    90,
    78
  ]
}

In [12]:
df = pd.DataFrame(data)

In [13]:
df

    Name  Age  Marks
0   John   22     85
1    Anu   21     90
2  Rahul   23     78

Inspecting Data

In [14]:
df.head()

    Name  Age  Marks
0   John   22     85
1    Anu   21     90
2  Rahul   23     78

In [15]:
df.tail()

    Name  Age  Marks
0   John   22     85
1    Anu   21     90
2  Rahul   23     78

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [17]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   22.0  84.333333
std     1.0   6.027714
min    21.0  78.000000
25%    21.5  81.500000
50%    22.0  85.000000
75%    22.5  87.500000
max    23.0  90.000000

In [18]:
df.shape

(3, 3)

In [19]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [20]:
df.dtypes

Name     object
Age       int64
Marks     int64
dtype: object

Selecting Data

Select One Column

In [21]:
df["Name"]

0     John
1      Anu
2    Rahul
Name: Name, dtype: object

In [22]:
df[
    ["Name","Marks"]
]

    Name  Marks
0   John     85
1    Anu     90
2  Rahul     78

loc and iloc are used to select data from a Series or DataFrame.

loc --> selects using labels

iloc--> selects using integer positions

In [23]:
df.loc[0]

Name     John
Age        22
Marks      85
Name: 0, dtype: object

In [25]:
df.loc[
    0,
    "Name"
]

'John'

In [26]:
df.loc[
    0:2,
    ["Name","Marks"]
]

    Name  Marks
0   John     85
1    Anu     90
2  Rahul     78

In [24]:
df.iloc[0]

Name     John
Age        22
Marks      85
Name: 0, dtype: object

In [27]:
df.iloc[
    0:2,
    0:2
]

   Name  Age
0  John   22
1   Anu   21

Position: 0,1,2,3

Label: John Anu Rahul Sara

Marks: 80 75 90 85

Data Manipulation

Add a Column

In [28]:
df["Passed"] = df["Marks"] >= 40

In [29]:
df

    Name  Age  Marks  Passed
0   John   22     85    True
1    Anu   21     90    True
2  Rahul   23     78    True